services:
  db:
    image: postgres:17
    container_name: stackinfo-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  scrape-daily:
    image: alal45643/stackinfo-scrape:dev
    build:
      context: ./
      dockerfile: ./Dockerfile.scrape
    environment:
      DATABASE_CONTAINER_NAME: ${DATABASE_CONTAINER_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}



volumes:
  postgres_data:
