FROM ghcr.io/astral-sh/uv:debian-slim
ENV PYTHONUNBUFFERED=1 PYTHONDONTWRITEBYTECODE=1
RUN mkdir /app
WORKDIR /app
COPY . .
RUN uv sync --frozen --no-cache
CMD [".venv/bin/fastapi", "run", "src/main.py", "--port", "80"]
