from typing import Sequence, cast
import asyncio
import datetime as dt
import os
import sys
import logging

from sqlalchemy import create_engine, select, Engine
from sqlalchemy.orm import Session

from scrape_workday import Scrape
from sql import (
    Locations,
    Stack_Count,
    Tech,
    Tech_Count,
    Tech_Parent_Tech,
    Tech_Stack_Count,
    Tech_Synonym,
    WorkdayURLs,
)

log = logging.getLogger(__name__)
logging.basicConfig(filename=f'logs/{str(dt.date.today())}.log', encoding='utf-8', level=logging.DEBUG)

def _create_engine() -> Engine:
    user = os.getenv("DATABASE_USERNAME")
    passw = os.getenv("DATABASE_PASSWORD")
    name = os.getenv("DATABASE_NAME")
    container = os.getenv("DATABASE_CONTAINER_NAME")
    engine = create_engine(
        f"postgresql+psycopg2://{user}:{passw}@{container}:5432/{name}"
    )
    return engine


def _query_scrape_params(
        engine: Engine,
) -> tuple[
    Sequence[str],
    Sequence[tuple[str, str]],
    list[str],
    list[str],
    dict[str, str],
    dict[str, str],
]:
    workday_urls_query = select(WorkdayURLs.url)
    location_query = select(Locations.city, Locations.state)
    sensitive_query = select(Tech.name).where(Tech.case_sensitive == True)
    insensitive_query = select(Tech.name).where(Tech.case_sensitive == False)
    synonym_query = select(Tech_Synonym.synonym, Tech_Synonym.name)
    parents_query = select(Tech_Parent_Tech.child_name, Tech_Parent_Tech.parent_name)
    with Session(engine) as session:
        workday_urls = session.scalars(workday_urls_query).all()
        locations = session.execute(location_query).all()
        sensitive = session.scalars(sensitive_query).all()
        insensitive = session.scalars(insensitive_query).all()
        synonyms = session.execute(synonym_query).all()
        parents = session.execute(parents_query).all()

    locations = cast(Sequence[tuple[str, str]], locations)
    synonyms = cast(Sequence[tuple[str, str]], synonyms)
    parents = cast(Sequence[tuple[str, str]], parents)

    sensitive = list(sensitive)
    insensitive = list(insensitive)
    synonyms = dict(synonyms)
    parents = dict(parents)
    return (workday_urls, locations, sensitive, insensitive, synonyms, parents)


def _export_results(
        engine: Engine,
        date: dt.date,
        techs: dict[tuple[tuple[str, str], str], int],
        stacks: dict[tuple[tuple[str, str], tuple[str]], int],
) -> None:
    with Session(engine) as session:
        for key, count in techs.items():
            tech = key[1]
            city = key[0][0]
            state = key[0][1]

            tech_count = Tech_Count(
                id=None, name=tech, city=city, state=state, count=count, date=date
            )
            session.add(tech_count)

        for key, count in stacks.items():
            stack = key[1]
            city = key[0][0]
            state = key[0][1]

            stack_count = Stack_Count(
                id=None, city=city, state=state, count=count, date=date
            )
            session.add(stack_count)
            # stack_count.id should be autogenerated after flush
            session.flush()

            for tech in stack:
                tech_stack_count = Tech_Stack_Count(
                    stack_count_id=stack_count.id, name=tech
                )
                session.add(tech_stack_count)

        session.commit()


async def _scrape(
        date: dt.date,
) -> tuple[
    dict[tuple[tuple[str, str], str], int],
    dict[tuple[tuple[str, str], tuple[str]], int],
]:
    log.info('creating engine')
    engine = _create_engine()

    log.info('retrieving parse_workday params')
    workday_urls, locations, sensitive, insensitive, synonyms, parents = (
        _query_scrape_params(engine)
    )

    log.info('creating Scrape class and task')
    scrape = Scrape(asyncio.Semaphore(3))
    task = asyncio.create_task(
        scrape.parse_workday(
            date,
            workday_urls,
            locations,
            sensitive,
            insensitive,
            synonyms,
            parents,
        )
    )

    log.info('awaiting scrape.parse_workday task')
    techs, stacks = await task

    log.info('exporting parse_workday tasks results')
    _export_results(engine, date, techs, stacks)

    return (techs, stacks)


def main(
        date: dt.date,
) -> tuple[
    dict[tuple[tuple[str, str], str], int],
    dict[tuple[tuple[str, str], tuple[str]], int],
]:
    return asyncio.run(_scrape(date))


if __name__ == "__main__":
    if len(sys.argv) == 2:
        print(main(dt.date.strptime(sys.argv[1], "%Y-%m-%d")))
    else:
        print("You need to specify a date.")
