import asyncio
import datetime as dt
import os
import sys

from sqlalchemy import create_engine, select
from sqlalchemy.orm import Session

from scrape_workday import Scrape
from sql import (
    Locations,
    Stack_Count,
    Tech,
    Tech_Count,
    Tech_Parent_Tech,
    Tech_Stack_Count,
    Tech_Synonym,
    WorkdayURLs,
)

# from scrape_workday import parse_workday


# get date
# get location_list
# get sensitive
# get insensitive
# get synonyms
# get parents
# get workday uris
# call parse_workday
# create database
# store in database
async def _scrape(date: dt.date):
    user = os.getenv("DATABASE_USERNAME")
    passw = os.getenv("DATABASE_PASSWORD")
    name = os.getenv("DATABASE_NAME")
    container = os.getenv("DATABASE_CONTAINER_NAME")
    engine = create_engine(
        f"postgresql+psycopg2://{user}:{passw}@{container}:5432/{name}"
    )

    workday_urls_query = select(WorkdayURLs.url)
    location_query = select(Locations.city, Locations.state)
    sensitive_query = select(Tech.name).where(Tech.case_sensitive == True)
    insensitive_query = select(Tech.name).where(Tech.case_sensitive == False)
    synonym_query = select(Tech_Synonym.synonym, Tech_Synonym.name)
    parents_query = select(Tech_Parent_Tech.child_name, Tech_Parent_Tech.parent_name)
    with Session(engine) as session:
        workday_urls = session.scalars(workday_urls_query).all()
        locations = session.execute(location_query).all()
        sensitive = session.scalars(sensitive_query).all()
        insensitive = session.scalars(insensitive_query).all()
        synonyms = session.execute(synonym_query).all()
        parents = session.execute(parents_query).all()

    synonyms = dict(synonyms)
    parents = dict(parents)
    scrape = Scrape(asyncio.Semaphore(3))
    task = asyncio.create_task(
        scrape.parse_workday(
            date,
            workday_urls,
            locations,
            list(sensitive),
            list(insensitive),
            synonyms,
            parents,
        )
    )
    res = await task

    with Session(engine) as session:
        techs = res[0]
        stacks = res[1]

        # create tech_count
        # add tech_count to session
        for key, count in techs.items():
            tech = key[1]
            city = key[0][0]
            state = key[0][1]

            tech_count = Tech_Count(
                id=None, name=tech, city=city, state=state, count=count, date=date
            )
            session.add(tech_count)

        for key, count in stacks.items():
            stack = key[1]
            city = key[0][0]
            state = key[0][1]

            stack_count = Stack_Count(
                id=None, city=city, state=state, count=count, date=date
            )
            session.add(stack_count)
            # stack_count.id should be autogenerated after flush
            session.flush()

            for tech in stack:
                tech_stack_count = Tech_Stack_Count(
                    stack_count_id=stack_count.id, name=tech
                )
                session.add(tech_stack_count)

        session.commit()

    return res


def main(date: dt.date) -> None:
    return asyncio.run(_scrape(date))


if __name__ == "__main__":
    if len(sys.argv) == 2:
        print(main(dt.date.strptime(sys.argv[1], "%Y-%m-%d")))
    else:
        print("You need to specify a date.")
